### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by halostatue** [rzane/file_store#23]
We finally got around to upgrading and there were a number of incompatibilities (the new `Prefix` middleware instead of `prefix:`, etc.).

It’s all good, but the current released version `0.2.2` only supports middleware for `FileStore.Config` versions where the configuration is specified in `config.exs`, but `master` appears to do the right thing (reading either `init` or `config` as appropriate). We use module-level configuration, not config.exs configuration.

A new release would alleviate this.

**Comment by rzane** [comment]
I just released a new version: https://hexdocs.pm/file_store/0.3.1

Please see breaking changes here: https://github.com/rzane/file_store/releases/tag/v0.3.0
